web:
  build: $PWD/docker/nginx
  ports:
    - 80:80
  links:
    - fpm:php
  volumes:
    - $PWD/wp:/var/www/html
fpm:
  build: $PWD/docker/phpfpm
  volumes:
    - $PWD/wp:/var/www/html
  links:
    - mysql:mysql
  ports:
    - 9000:9000
mysql:
  build: $PWD/docker/mysql
  ports:
    - 3306:3306
  volumes:
    - $PWD/sql:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=wordpress